name: 01 - Building Blocks

on:
  push

jobs:
  echo-hello:
    runs-on:
      ubuntu-latest
    steps:
      - run: echo "Hello, World!"

  echo-goodbye:
    runs-on:
      ubuntu-latest
    steps:
      - run: echo "Goodbuy!"
