name: Specific Path Change

on:
  push:
    paths:
      - 'src/**'      # Any changes in the 'src' folder
      - 'README.md'   # changes in Readme file

jobs:
  path-change-job:
    runs-on: ubuntu-latest
    steps:
      - name: List Modified Files
        run: |
          echo "The following files triggered this workflow:"
          echo "${{ github.event.head_commit.modified }}"
